pipeline {
  agent any
  environment {
    withCredentials([usernamePassword(
      credentialsId: credentials('mzc-trg-lsj'),
      accessKeyVariable: 'AWS_ACCESS_KEY_ID',
      secretKeyVariable: 'AWS_SECRET_ACCESS_KEY')]) {
    }
    region = string('region')
  }
  stages {
    stage('Packer') {
      steps {
        sh """
        #!/bin/bash
        cd packer_build_test
        packer init .
        packer build --var access_key=${env.AWS_ACCESS_KEY_ID} secret_key=${env.AWS_SECRET_ACCESS_KEY} region=${env.region} .
        """
      }
    }
  }
}