pipeline {
  agent any
  stages {
    stage('Packer') {
      steps {
        withAWS(credentials: 'AWS_Credentials') {
        sh """
        echo $AWS_ACCESS_KEY_ID
        echo $AWS_SECRET_ACCESS_KEY
        """
      }
    }
  }
}
}